Repository nss-evening-cohort-14/pan-am-group-project, pull requests merged in 2021-03, with the labels that each got.

#19 Development Branch
  .DS_Store
  .env
  node_modules/.DS_Store
  sample_json_data.js/airport.json
  sample_json_data.js/baggage.json
  sample_json_data.js/crew.json
  sample_json_data.js/foodService.json
  sample_json_data.js/plane.json
  src/.DS_Store
  src/javascripts/.DS_Store
Labels: enhancement

#4 Setup
  README.md
Labels: good first issue

#49 View planes
  src/javascripts/components/forms/domBuilder.js
  src/javascripts/components/forms/editPlaneForm.js
  src/javascripts/components/forms/planeForm.js
  src/javascripts/components/forms/planeFormModal.js
  src/javascripts/components/planes.js
  src/javascripts/events/navEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/planeData.js
  src/javascripts/views/startApp.js
  src/styles/main.scss
Labels: enhancement

#53 Fixed sass issue
  package.json
Labels: bug

#61 Bj create planes final
  src/javascripts/components/forms/addPlaneForm.js
  src/javascripts/components/planes.js
  src/javascripts/events/navEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/planeData.js
  src/javascripts/views/startApp.js
Labels: enhancement

#62 Create Baggage Functionality
  src/javascripts/components/baggage.js
  src/javascripts/components/crew.js
  src/javascripts/components/food.js
  src/javascripts/components/forms/addBaggageForm.js
  src/javascripts/events/baggageDomEvents.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/navEvents.js
  src/javascripts/helpers/data/baggageData.js
  src/javascripts/views/startApp.js
Labels: enhancement

#63 Create Crew Functional
  PULL_REQUESTS.md
  src/index.html
  src/javascripts/components/baggage.js
  src/javascripts/components/crew.js
  src/javascripts/components/forms/addBaggageForm.js
  src/javascripts/components/forms/addCrewForm.js
  src/javascripts/events/airportDomEvents.js
  src/javascripts/events/baggageDomEvents.js
  src/javascripts/events/crewDomEvent.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/crewData.js
  src/javascripts/views/domBuilder.js
  src/javascripts/views/startApp.js
Labels: enhancement

#65 Bj dev final
  src/javascripts/components/forms/addFoodForm.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/navEvents.js
  src/javascripts/views/startApp.js
  src/styles/airport.scss
Labels: enhancement

#66 fixed last console.warn
  src/javascripts/events/foodDomEvents.js
Labels: enhancement

#64 CREATE MILESTONE
  PULL_REQUESTS.md
  src/index.html
  src/javascripts/components/baggage.js
  src/javascripts/components/crew.js
  src/javascripts/components/food.js
  src/javascripts/components/forms/addAirportForm.js
  src/javascripts/components/forms/addBaggageForm.js
  src/javascripts/components/forms/addCrewForm.js
  src/javascripts/components/forms/addFoodForm.js
  src/javascripts/components/forms/addPlaneForm.js
  src/javascripts/components/planes.js
  src/javascripts/events/airportDomEvents.js
  src/javascripts/events/baggageDomEvents.js
  src/javascripts/events/crewDomEvent.js
  src/javascripts/events/domEvents.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/navEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/airportData.js
  src/javascripts/helpers/data/baggageData.js
  src/javascripts/helpers/data/crewData.js
  src/javascripts/helpers/data/foodData.js
  src/javascripts/helpers/data/planeData.js
  src/javascripts/views/domBuilder.js
  src/javascripts/views/startApp.js
  src/styles/airport.scss
  src/styles/main.scss
Labels: enhancement

#70 delete planes
  sample_json_data.js/planes.json
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/planeData.js
  src/javascripts/views/startApp.js
Labels: enhancement

#71 Nk delete food
  sample_json_data.js/foodServices.json
  src/javascripts/components/food.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/helpers/data/foodData.js
Labels: enhancement

#72 Delete Crews
  src/javascripts/events/crewDomEvent.js
Labels: bug

#73 Development
  sample_json_data.js/foodServices.json
  sample_json_data.js/planes.json
  src/javascripts/components/airports.js
  src/javascripts/components/baggage.js
  src/javascripts/components/food.js
  src/javascripts/events/airportDomEvents.js
  src/javascripts/events/baggageDomEvents.js
  src/javascripts/events/crewDomEvent.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/airportData.js
  src/javascripts/helpers/data/baggageData.js
  src/javascripts/helpers/data/crewData.js
  src/javascripts/helpers/data/foodData.js
  src/javascripts/helpers/data/planeData.js
  src/javascripts/views/startApp.js
Labels: enhancement

#74 Update Crew Feature Functional
  src/javascripts/components/crew.js
  src/javascripts/components/forms/addCrewForm.js
  src/javascripts/components/forms/editCrewForm.js
  src/javascripts/events/crewDomEvent.js
  src/javascripts/helpers/data/crewData.js
Labels: enhancement

#75 baggage update functional
  src/javascripts/components/baggage.js
  src/javascripts/components/crew.js
  src/javascripts/components/forms/addBaggageForm.js
  src/javascripts/components/forms/editBaggageForm.js
  src/javascripts/events/baggageDomEvents.js
  src/javascripts/events/crewDomEvent.js
  src/javascripts/helpers/data/baggageData.js
  src/javascripts/helpers/data/crewData.js
Labels: enhancement

#84 added Update Functionality
  src/javascripts/components/airports.js
  src/javascripts/components/forms/addAirportForm.js
  src/javascripts/components/forms/editAirportForm.js
  src/javascripts/events/airportDomEvents.js
  src/javascripts/helpers/data/airportData.js
  src/javascripts/helpers/data/planeData.js
Labels: enhancement

#85 Bj edit planes
  src/javascripts/components/forms/editPlaneForm.js
  src/javascripts/components/planes.js
  src/javascripts/events/foodDomEvents.js
  src/javascripts/events/navEvents.js
  src/javascripts/events/planeDomEvents.js
  src/javascripts/helpers/data/planeData.js
Labels: enhancement

#90 added basic styling
  src/javascripts/components/baggage.js
  src/javascripts/components/crew.js
  src/javascripts/components/food.js
  src/javascripts/components/forms/addAirportForm.js
  src/javascripts/components/forms/editAirportForm.js
  src/javascripts/components/navBar.js
  src/javascripts/components/planes.js
  src/javascripts/events/navEvents.js
  src/styles/baggage.scss
  src/styles/main.scss
Labels: enhancement
